guokr/swagger-py-codegen

swagger_py_codegen/resolver.py, swagger_py_codegen/templates/requirements.tpl
1. create missing arg for schema
2. request method ordered in api files
=> method ordered in api+

README.md
Reverts guokr/swagger-py-codegen#9
=> Revert "udpate README"

swagger_py_codegen/jsonschema.py, swagger_py_codegen/templates/flask/validators.tpl
- Fixes headers filter bug.
- Fixes json encode exception of datetime.
- Use isoformat(ISO8601) as json datetime format.
- Use response_class replace flask.Response.
- response_filter return response instance directly, for avoid flask-restful process more.
=> Improve validator

swagger_py_codegen/templates/flask/validators.tpl
=> fix bug about issue22

swagger_py_codegen/jsonschema.py
=> fix bug about issue26

README.md
=> Underscores in command, not dashes

swagger_py_codegen/__init__.py, swagger_py_codegen/templates/ui/index.html
Minor fix to address making the index.html point to the right location.
=> Making the `index.html` point to the local swagger.json.

README.md, swagger_py_codegen/__init__.py, swagger_py_codegen/jsonschema.py, tests/test_jsonschema.py
=> Fix issue 42

swagger_py_codegen/flask.py
Change example object like example in http://swagger.io/specification/#exampleObject.
=> Change example object

swagger_py_codegen/jsonschema.py, swagger_py_codegen/templates/flask/app.tpl, swagger_py_codegen/templates/flask/validators.tpl
1. fix six import issue
2. fix compatible bug in validators
3. modify v1 package import method
=> 78 fix six import

setup.py, swagger_py_codegen/command.py, swagger_py_codegen/parser.py
Speed up processing by using multiprocessing and LRU cache
=> Speedup processing

setup.py, swagger_py_codegen/__init__.py, swagger_py_codegen/_version.py, swagger_py_codegen/command.py
add version command option
`swagger_py_codegen --version`
=> [Add] version command option

swagger_py_codegen/jsonschema.py, tests/test_jsonschema.py
support `additionalProperties: true` and `additionalProperties: {}`
=> fixes additionalProperties

swagger_py_codegen/_version.py
tornado requirements add `werkzeug`
=> fix_issue_104

swagger_py_codegen/jsonschema.py, swagger_py_codegen/parser.py, swagger_py_codegen/templates/falcon/validators.tpl, swagger_py_codegen/templates/flask/validators.tpl, swagger_py_codegen/templates/jsonschema/schemas.tpl, swagger_py_codegen/templates/sanic/validators.tpl, swagger_py_codegen/templates/tornado/validators.tpl, tests/test_jsonschema.py, tests/test_parser.py
Reverts guokr/swagger-py-codegen#118
=> Revert "resolver"

swagger_py_codegen/sanic.py, swagger_py_codegen/templates/sanic/schemas.tpl
=> fix sanic schema and py3 compatible error

README.md, requirements.txt, swagger_py_codegen/_version.py, swagger_py_codegen/command.py
fixes `TypeError: generate() got an unexpected keyword argument 'swagger'`
=> fixes click

swagger_py_codegen/jsonschema.py
like this
```yaml
definitions:
A:
properties:
parent:
$ref: '#/definitions/A'
```
=> fixes RecursionError

swagger_py_codegen/jsonschema.py
This reverts commit 558f0b817d40d5c3e4ce23026de96156786413fa.
=> Revert "fixes RecursionError"

swagger_py_codegen/templates/jsonschema/schemas.tpl
生成的代码里并没有用到RefNode, 将那部分代码拷过去, 有定义即可
=> remove swagger_py_codegen require
